In [11]:
#soru 1
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
benzersiz = []
for i in notlar:
    if i not in benzersiz:
        benzersiz.append(i)
print(benzersiz)
en_buyuk=max(benzersiz)
en_kucuk=min(benzersiz)
benzersiz.sort()

print(benzersiz)
print(f"En büyük değer: {en_buyuk}")
print(f"En küçük değer: {en_kucuk}")


[85, 92, 76, 100]
[76, 85, 92, 100]
En büyük değer: 100
En küçük değer: 76


In [9]:
#soru 2
def armstrong():
    value =input("bir sayı giriniz:")
    liste_1=[int(rakam) for rakam in value]
    liste_2=[sayi**3 for sayi in liste_1]
    if sum(liste_2)==int(value):
        print("Armstrong sayısı")
    else: print("Armstrong sayısı değil")
    
    
armstrong()





bir sayı giriniz: 5486


Armstrong sayısı değil


In [27]:
#soru 3
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
print(A.intersection(B))
print(A.difference(B))
birlesim = A.union(B)
liste=sorted(birlesim)
print(liste)

{'Python', 'SQL'}
{'Java', 'R'}
['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [33]:
#soru 4
import random
import statistics

sayilar=[random.randint(1,101) for _ in range(5)]
print(sayilar)
ortalama = statistics.mean(sayilar)
st_sapma = statistics.stdev(sayilar)
print(f"ortalama: {ortalama}")
print(f"st_sapma: {st_sapma}")


[48, 88, 92, 73, 44]
ortalama: 69
st_sapma: 22.20360331117452


In [49]:
#5
def kelime_sayaci(metin):
    
    kelimeler = metin.split()  
    toplam = len(kelimeler)
    en_uzun = ""
    for kelime in kelimeler:
        if len(kelime) > len(en_uzun):
            en_uzun = kelime
    
    en_sik = ""
    en_sayi = 0
    
    for kelime in kelimeler:
        adet = kelimeler.count(kelime)
        if adet > en_sayi:
            en_sayi = adet
            en_sik = kelime
    return toplam, en_uzun, en_sik
    
metin = input("Bir metin giriniz: ")

sonuc = kelime_sayaci(metin)
print("Toplam kelime sayısı:", sonuc[0])
print("En uzun kelime:", sonuc[1])
print("En sık geçen kelime:", sonuc[2])


Bir metin giriniz:  The Machine Learning Specialization is a foundational online program created in collaboration between DeepLearning.


Toplam kelime sayısı: 14
En uzun kelime: Specialization
En sık geçen kelime: The


In [37]:
#soru 6
sayilar = [5, 12, 7, 18, 24, 3, 16]

ciftler = filter(lambda x: x % 2 == 0, sayilar)

kareler = map(lambda x: x ** 2, ciftler)

sonuc = sorted(kareler, reverse=True)

print(list(sonuc))


[576, 324, 256, 144]


In [38]:
#soru 7
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

sirali = sorted(kelimeler, key=lambda x: len(x))

print(sirali)

    

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [3]:
#soru 8
def rakamlar():
    kelime = "abc12def3"
    sayilar = [int(karakter) for karakter in kelime if karakter.isdigit()]
    return sum(sayilar)

print(rakamlar())

6


In [46]:
#soru 7
import numpy as np
sayilar=np.random.randint(0,51,10)
print(sayilar)

ort=np.mean(sayilar)
std=np.std(sayilar)
en_buyuk=np.max(sayilar)

print(f"ortalama: {ort}")
print(f"standart sapma: {std}")
print(f"en büyük değer: {en_buyuk}")

[12  0 42 50 35 47 41 40 35  9]
ortalama: 31.1
standart sapma: 16.603915200939806
en büyük değer: 50


In [48]:
#soru 8
import numpy as np

matris = np.random.rand(5, 5)
print("Orijinal Matris:\n", matris)

sutun_ortalama = np.mean(matris, axis=0)
print("\nHer sütunun ortalaması:", sutun_ortalama)

binary_matris = np.where(matris > 0.5, 1, 0)
print("\nBinary Matris:\n", binary_matris)


Orijinal Matris:
 [[0.15756217 0.32313989 0.02672266 0.0391449  0.76673833]
 [0.37605835 0.06972225 0.18530415 0.41824061 0.89982573]
 [0.57218123 0.62538673 0.07246724 0.32802108 0.47839945]
 [0.67253424 0.44333253 0.52811397 0.16510367 0.40287145]
 [0.4517828  0.05784102 0.18497672 0.14803635 0.36489971]]

Her sütunun ortalaması: [0.44602376 0.30388448 0.19951695 0.21970933 0.58254694]

Binary Matris:
 [[0 0 0 0 1]
 [0 0 0 0 1]
 [1 1 0 0 0]
 [1 0 1 0 0]
 [0 0 0 0 0]]
